spring.application.name=${spring.application.name}
server.port=${server.port}

spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.datasource.driver-class-name=${spring.datasource.driver-class-name}



spring.jpa.database-platform=${spring.jpa.database-platform}
spring.jpa.hibernate.ddl-auto=${spring.jpa.hibernate.ddl-auto}
spring.jpa.show-sql=${spring.jpa.show-sql}
spring.jpa.properties.hibernate.format_sql=${spring.jpa.properties.hibernate.format_sql}

spring.security.oauth2.client.registration.github.client-id=${spring.security.oauth2.client.registration.github.client-id}
spring.security.oauth2.client.registration.github.client-secret=${spring.security.oauth2.client.registration.github.client-secret}


github.security.algorithm = ${github.security.algorithm}
github.security.secret = ${github.security.secret}
github.base.api.url=${github.base.api.url}

frontend.url = http://localhost:3000

jwt.secret.private =classpath:private.pem
jwt.secret.public =classpath:public.pem

spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize